apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-management-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-management-system
  template:
    metadata:
      labels:
        app: hr-management-system
    spec:
      containers:
        - name: hr-management-system
          image: your-dockerhub-username/hr-management-system:latest
          ports:
            - containerPort: 5000
